name: Kaitolobby
version: '${project.version}'
main: de.kaitokid1513.lobby.main
api-version: '1.21'
commands:
  build:

  setspawn:

  spawn:

  setwarp:

  warp:

  delwarp:

  fly:

  plugins:
    aliases: [pl]

  social: